### PR TITLE
Fix 576 adding multi-project Gradle support

### LINKED ISSUE #576: Gradle multi-project support
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details
A "mono-repo" approach is currently not supported (at least ootb) through grade as `pulumi` is invoking everything from the current folder instead of using Gradle with correct args such as the subproject name.

A simple setup containing two separate pulumi projects with different stacks. They are defined as two separate subprojects `:services:app-cluster` and `:services:mgmt-cluster`.

*root settings.gradle(.kts)*
```
rootProject.name = "iac"
include(
    "libs:modules",
    "services:app-cluster",
    "services:mgmt-cluster",
    "testing:commons",
)
```

*Simplified dir structure*
```
settings.gradle
build.gradle
services/
  -> app-cluster/
       * build.gradle
       * Pulumi.yaml
       * Pulumi.dev.yaml
       * Pulumi.staging.yaml
       * Pulumi.production.yaml
   -> mgmt-cluster/
       * build.gradle
       * Pulumi.yaml
       * Pulumi.production.yaml
```

You shouldn't need to have any `settings.gradle` inside of the subproject directories but trying to run pulumi inside one of the subprojects you get the following error message.
```
error: failed to load language plugin java: could not read plugin [/home/nickjn92/.pulumi/bin/pulumi-language-java] stdout: EOF
```

Also it might be classic pebcak but I'm currently getting errors trying to run this by adding `gradle.settings` to each subproject and running `pulumi up` from those directories
```
  pulumi:pulumi:Stack (iac-app-cluster-kotlin-dev):
    Exception in thread "main" java.lang.IllegalArgumentException: Program run without the Pulumi engine available; re-run using the `pulumi` CLI
...
Caused by: java.lang.IllegalArgumentException: expected environment variable: 'PULUMI_MONITOR', got: ...

```

### PR DESCRIPTION
**Pull request by t0yv0**
# Description

Factors out executors and improves mutli-project gradle executor detection.

Fixes #576 

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works

- [ ] I have updated the [CHANGELOG-PENDING](https://github.com/pulumi/pulumi/blob/master/CHANGELOG_PENDING.md) file with my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

File: pkg/internal/executors/executor_test.go [hunk 1]
```diff
@@ -0,0 +1,252 @@
...
+import (
+	"testing"
+	"testing/fstest"
+
+	"github.com/stretchr/testify/assert"
+
+	"github.com/pulumi/pulumi-java/pkg/internal/fsys"
+)
+
+func TestGradleSimple(t *testing.T) {
```
Comment (pawelprazak) [inline pkg/internal/executors/executor_test.go:14]: nice! unit test!

**Review by pawelprazak — APPROVED** [review]
