### PR TITLE
[program-gen] Emit invoke options and invoke output options in generated programs

### LINKED ISSUE #1566: Fix `l2-resource-config` / plugin download URL code generation
The `l2-resource-config` conformance test currently fails due to some values not lining up. It looks like we are not respecting plugin download URLs (at least -- there may be other things we are missing).

```
=== NAME  TestLanguage/l2-resource-config
    language_test.go:146: l2_resource_config.go:56: 
                Error Trace:    /home/will/git/pulumi/pulumi-java-main/pulumi/cmd/pulumi-test-language/tests/l2_resource_config.go:56
                                                        /home/will/git/pulumi/pulumi-java-main/pulumi/cmd/pulumi-test-language/interface.go:1098
                                                        /home/will/git/pulumi/pulumi-java-main/pulumi/cmd/pulumi-test-language/tests/types.go:182
                                                        /nix/store/chzgk756zb2cqlzbjr86m0lfxi63cdfy-go-1.22.7/share/go/src/runtime/asm_amd64.s:1695
                Error:          Not equal: 
                                expected: resource.PropertyMap{"__internal":resource.PropertyValue{V:resource.PropertyMap{"pluginDownloadURL":resource.PropertyValue{V:"http://example.com"}}}, "name":resource.PropertyValue{V:"my config"}, "pluginDownloadURL":resource.PropertyValue{V:"not the same as the pulumi resource option"}, "version":resource.PropertyValue{V:"9.0.0"}}
                                actual  : resource.PropertyMap{"__internal":resource.PropertyValue{V:resource.PropertyMap{}}, "name":resource.PropertyValue{V:"my config"}, "pluginDownloadURL":resource.PropertyValue{V:"not the same as the pulumi resource option"}, "version":resource.PropertyValue{V:"9.0.0"}}
                            
                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -2,6 +2,3 @@
                                  (resource.PropertyKey) (len=10) "__internal": (resource.PropertyValue) {
                                -  V: (resource.PropertyMap) (len=1) {
                                -   (resource.PropertyKey) (len=17) "pluginDownloadURL": (resource.PropertyValue) {
                                -    V: (string) (len=18) "http://example.com"
                                -   }
                                +  V: (resource.PropertyMap) {
                                   }
        
    language_test.go:148: stdout: Created stack 'test'
        
         +  pulumi:pulumi:Stack l2-resource-config-test creating (0s) 
         +  pulumi:providers:config prov creating (0s) 
         +  pulumi:providers:config prov created (0.00s) 
         +  config:index:Resource res creating (0s) 
         +  config:index:Resource res created (0.00s) 
         +  pulumi:pulumi:Stack l2-resource-config-test created (0.44s) 
        Outputs:
            pluginDownloadURL: "not the same as the pulumi resource option"
        
        Resources:
            + 3 created
        
        Duration: 3s
        
    language_test.go:149: stderr: 
    language_test.go:150: 
                Error Trace:    /home/will/git/pulumi/pulumi-java-main/pkg/cmd/pulumi-language-java/language_test.go:150
                Error:          Should be true
                Test:           TestLanguage/l2-resource-config
--- FAIL: TestLanguage (10.95s)
    --- FAIL: TestLanguage/l2-resource-config (12.69s)
FAIL
FAIL    github.com/pulumi/pulumi-java/pkg/cmd/pulumi-language-java      23.662s
FAIL
```

### PR DESCRIPTION
**Pull request by Zaid-Ajaj**
Built on top of https://github.com/pulumi/pulumi-java/pull/1585 in order to generate `InvokeOptions` for invoke calls. 

- Fixes #1566
- Unskips `l2-invoke-options`
- Implements optimized import handling when encountering function calls
- Implements lambda parameter shadowing when generating `apply(...)` 
    - `data.applyValue(data -> data.result())` becomes `data.applyValue(_data -> _data.result())`
- Fixes `apply(...)` calls for invokes when used in output variables

This PR prepares program-gen and sdk to handle `l2-invoke-options-depends-on` which currently generate correct programs but fails the actual conformance test where the invoke has no dependencies cc @julienp

### CODE REVIEW

File: pkg/codegen/testing/test/testdata/aws-fargate-pp/java/aws-fargate.java [hunk 1]
```diff
@@ -95,15 +95,15 @@ public static void stack(Context ctx) {
 
         // Create a load balancer to listen for HTTP traffic on port 80.
         var webLoadBalancer = new LoadBalancer("webLoadBalancer", LoadBalancerArgs.builder()
-            .subnets(subnets.applyValue(getSubnetIdsResult -> getSubnetIdsResult.ids()))
+            .subnets(subnets.ids())
```
Comment (Zaid-Ajaj) [inline pkg/codegen/testing/test/testdata/aws-fargate-pp/java/aws-fargate.java:98]: This change doesn't look right
```java
.subnets(subnets.ids())
```
should be 
```java
.subnets(subnets.applyValue(getSubnetIdsResult -> getSubnetIdsResult.ids()))
```
Investigating the problem...

Comment (Zaid-Ajaj) [reply pkg/codegen/testing/test/testdata/aws-fargate-pp/java/aws-fargate.java]: Fixed by enabling `PreferOutputVersionedInvokes` bind option in the program-gen tests so that invoke get the right type i.e. `Output<InvokeResult>` ✅

File: pkg/codegen/java/gen_program.go [hunk 2]
```diff
@@ -807,9 +837,37 @@ func (g *generator) genPreamble(w io.Writer, nodes []pcl.Node) {
...
+			functionImports.Add("com.pulumi.asset.RemoteAsset")
+		case "assetArchive":
+			functionImports.Add("com.pulumi.asset.AssetArchive")
+		case pcl.Invoke:
+			if len(call.Args) == 3 && containsDependsOnInvokeOption(call.Args[2]) {
+				// for invoke output options, instantiate the builder from its parent class
+				// i.e. (new InvokeOutputOptions.Builder()).dependsOn(resource).build()
+				functionImports.Add("com.pulumi.deployment.InvokeOutputOptions")
+			} else if len(call.Args) == 3 {
+				functionImports.Add("com.pulumi.deployment.InvokeOptions")
```
Comment (lunaris) [inline pkg/codegen/java/gen_program.go:864]: Maybe tweak this to just check the length once?

```java
if len(call.Args) == 3 {
  // Comments as above etc.
  if containsDependsOnInvokeOption(call.Args[2]) {

  } else {

  }
}
```

File: pkg/codegen/java/gen_program.go [hunk 3]
```diff
@@ -152,6 +152,23 @@ func containsFunctionCall(functionName string, nodes []pcl.Node) bool {
 	return foundRangeCall
 }
 
+func inspectFunctionCall(nodes []pcl.Node, inspect func(*model.FunctionCallExpression)) {
+	for _, node := range nodes {
+		diags := node.VisitExpressions(model.IdentityVisitor, func(x model.Expression) (model.Expression, hcl.Diagnostics) {
+			// Ignore the node if it is not a call to invoke.
```
Comment (lunaris) [inline pkg/codegen/java/gen_program.go:158]: I reckon just add a doc comment to the function explaining what it's doing, then you don't need this line (which I think applies to more than just invokes anyway -- any built-in would also trigger it, right?

File: pkg/codegen/java/gen_program_expressions.go [hunk 4]
```diff
@@ -83,7 +83,27 @@ func (g *generator) GenAnonymousFunctionExpression(w io.Writer, expr *model.Anon
 	case 0:
 		g.Fgen(w, "()")
 	case 1:
-		g.Fgenf(w, "%s", expr.Signature.Parameters[0].Name)
+		// rename the parameter to avoid conflicts existing variables
+		// for example we could have data.applyValue(data -> data.result())
+		// in this case we rename the parameter to _data
+		// it becomes data.applyValue(_data -> _data.result())
+		paramName := expr.Signature.Parameters[0].Name
+		modifiedParamName := "_" + paramName
```
Comment (lunaris) [inline pkg/codegen/java/gen_program_expressions.go:91]: I suspect this isn't safe in general (there might be another variable named `_data` in scope, for instance) but it's probably a good starting point for now. Probably should add another conformance test around shadowing etc. in future.

**Review by lunaris — APPROVED** [review]

File: pkg/codegen/java/gen_program.go (hunk 2 above)
Comment (Zaid-Ajaj) [reply pkg/codegen/java/gen_program.go]: Done ✅

File: pkg/codegen/java/gen_program.go (hunk 3 above)
Comment (Zaid-Ajaj) [reply pkg/codegen/java/gen_program.go]: Added better docs ✅
