### PR TITLE
Fix broken URN parsing on nested parents.

### LINKED ISSUE #1045: Issue with creating AWSX resources (Vpc) with the Java SDK
### What happened?

When creating a Vpc resource (from Crosswalk, under `com.pulumi.awsx.ec2.*`) pulumi reports an error related to the resource URN generation. Somewhere in the chain of validating the resource URN there is a failure within one of the Java library methods. The stacktrace is as follows:

```
java.lang.IllegalArgumentException: expected qualified type to have 1 or 2 parts, split by '\$', got 'awsx:ec2:Vpc, aws:ec2/vpc:Vpc, aws:ec2/internetGateway:InternetGateway'
        at com.pulumi.core.internal.Objects.require(Objects.java:34)
        at com.pulumi.core.internal.Objects.require(Objects.java:48)
        at com.pulumi.core.internal.Urn$QualifiedTypeName.parse(Urn.java:178)
        at com.pulumi.core.internal.Urn.parse(Urn.java:131)
        at com.pulumi.serialization.internal.Deserializer.tryDeserializeResource(Deserializer.java:365)
        at com.pulumi.serialization.internal.Deserializer.deserializeCore(Deserializer.java:103)
        at com.pulumi.serialization.internal.Deserializer.deserialize(Deserializer.java:59)
        at com.pulumi.serialization.internal.Converter.convertValue(Converter.java:81)
        at com.pulumi.core.internal.OutputCompletionSource.setValue(OutputCompletionSource.java:95)
        at com.pulumi.deployment.internal.DeploymentImpl$ReadOrRegisterResourceInternal.lambda$completeResourceAsync$0(DeploymentImpl.java:1193)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
        at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

### Expected Behavior

The VPC should be created as expected with the correct subnet specs.

### Steps to reproduce

1. Create a new pulumi project using `mkdir awsx-pulumi-issue && cd awsx-pulumi-issue && pulumi new java-gradle`. Answer the questionnaire with any defaults you prefer.
2. In the generated code directory, add the following line in `app/build.gradle` under the `dependencies` section: `   implementation 'com.pulumi:awsx:1.0.2'` 
3. In the generated code, replace the contents of `app/src/main/java/myproject/App.java` with

```
package myproject;

import com.pulumi.Pulumi;
import com.pulumi.awsx.ec2.Vpc;
import com.pulumi.awsx.ec2.VpcArgs;
import com.pulumi.awsx.ec2.enums.NatGatewayStrategy;
import com.pulumi.awsx.ec2.enums.SubnetType;
import com.pulumi.awsx.ec2.inputs.NatGatewayConfigurationArgs;
import com.pulumi.awsx.ec2.inputs.SubnetSpecArgs;

public class App {
    public static void main(String[] args) {
        Pulumi.run(ctx -> {
            Vpc vpc = new Vpc(
                    "example-private-vpc",
                    VpcArgs.builder()
                            .subnetSpecs(
                                    SubnetSpecArgs.builder()
                                            .type(SubnetType.Private)
                                            .cidrMask(22)
                                            .build()
                            )
                            .natGateways(
                                    NatGatewayConfigurationArgs.builder()
                                            .strategy(NatGatewayStrategy.None)
                                            .build()
                            )
                            .build()
            );

            ctx.export("privateVpcId", vpc.vpcId());
        });
    }
}
```

The above might even be a little more elaborate than required to reproduce this issue. Even the following fails with the exact same error:

```
Pulumi.run(ctx -> {
            Vpc vpc = new Vpc(
                    "example-private-vpc"
            );

            ctx.export("privateVpcId", vpc.vpcId());
        });
```

4. In the pulumi code directory, run `pulumi up`

### Output of `pulumi about`

```
CLI          
Version      3.46.1
Go Version   go1.19.3
Go Compiler  gc

Plugins
NAME  VERSION
aws   5.16.2
awsx  1.0.2
java  unknown

Host     
OS       arch
Version  "rolling"
Arch     x86_64

This project is written in java: executable='/usr/bin/java' version='openjdk 17.0.6 2023-01-17
OpenJDK Runtime Environment (build 17.0.6+10)
OpenJDK 64-Bit Server VM (build 17.0.6+10, mixed mode)' java='/usr/bin/java' javac='17.0.6' maven='Apache Maven 3.8.7 (b89d5959fcde851dcb1c8946a785a163f14e1e29)' gradle='8.0.2'

Current Stack: awsx-pulumi-issue

Found no resources associated with awsx-pulumi-issue

Found no pending operations associated with awsx-pulumi-issue

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/rohanprabhu
User           rohanprabhu
Organizations  rohanprabhu, commandk

No dependencies found

Pulumi locates its logs in /tmp by default
```

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by dixler**
# Description
Added failing test case for nested parenting in resource URN. Changed Parent from Optional<Type> to Optional<String>.

Fixes #1045

## Checklist

- [x] I have added tests that prove my fix is effective or that my feature works

- [x] I have updated the [CHANGELOG-PENDING](https://github.com/pulumi/pulumi/blob/master/CHANGELOG_PENDING.md) file with my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

File: sdk/java/pulumi/src/test/java/com/pulumi/core/internal/UrnTest.java [hunk 1]
```diff
@@ -127,7 +136,7 @@ private static Stream<Arguments> testCreateUrnString() {
                         "stack", "project",
                         Optional.of("urn:pulumi:stack::project::parentPackage:parentType$package:type::name"),
                         "package2:type2", "name2",
-                        "urn:pulumi:stack::project::package:type$package2:type2::name2"
+                        "urn:pulumi:stack::project::parentPackage:parentType$package:type$package2:type2::name2"
```
Comment (dixler) [inline sdk/java/pulumi/src/test/java/com/pulumi/core/internal/UrnTest.java:139]: I believe the original test case was incorrect because there should be 2 parents in the type since the parent resource itself has a parent.

File: sdk/java/pulumi/src/main/java/com/pulumi/core/internal/Urn.java [hunk 2]
```diff
@@ -148,10 +150,10 @@ public String asString() {
     @ParametersAreNonnullByDefault
     @SuppressWarnings("OptionalUsedAsFieldOrParameterType")
     public static final class QualifiedTypeName {
-        public final Optional<Type> parent;
+        public final Optional<String> parent;
```
Comment (dixler) [inline sdk/java/pulumi/src/main/java/com/pulumi/core/internal/Urn.java:153]: This is an internal package so I believe it should be safe to change this.

**Comment by dixler** [comment]
I have verified that the change fixes the bug when switching from an old version to the new version tested locally on my machine.

recording: https://asciinema.org/a/ejFDCEUUFxikr3vPhaqIpKdEJ

File: sdk/java/pulumi/src/main/java/com/pulumi/core/internal/Urn.java [hunk 3]
```diff
@@ -181,7 +183,7 @@ public String toString() {
         @SuppressWarnings("ConstantConditions") // IntelliJ can't understand the custom validators
         public static QualifiedTypeName parse(String qualifiedType) {
             var qualifiedTypeParts = qualifiedType.split(ParentSeparatorRegex, -1); // -1 avoids dropping trailing empty strings
-            require(qp -> qp.length == 1 || qp.length == 2, qualifiedTypeParts,
+            require(qp -> qp.length > 0, qualifiedTypeParts,
                     () -> format("expected qualified type to have 1 or 2 parts, split by '%s', got '%s'",
```
Comment (Frassle) [inline sdk/java/pulumi/src/main/java/com/pulumi/core/internal/Urn.java:187]:
```suggestion
                    () -> format("expected qualified type to not be empty, split by '%s', got '%s'",
```

File: sdk/java/pulumi/src/main/java/com/pulumi/core/internal/Urn.java [hunk 4]
```diff
@@ -190,20 +192,29 @@ public static QualifiedTypeName parse(String qualifiedType) {
...
             );
             final Optional<String> parent;
-            if (qualifiedTypeParts.length == 2) {
-                var pt = qualifiedTypeParts[0];
+
+            // Handle parents. URNs can have nested parents which should be joined with a "$".
+            if (qualifiedTypeParts.length >= 2) {
+                // Remove the last qualifiedTypeParts element as it's the type.
+                String[] parentList = new String[qualifiedTypeParts.length - 1];
+                var pt = String.join(ParentSeparator, parentList);
```
Comment (Frassle) [inline sdk/java/pulumi/src/main/java/com/pulumi/core/internal/Urn.java:200]: parentList is empty at this point?

File: tests/examples/minimal/pom.xml [hunk 5]
```diff
@@ -75,6 +75,14 @@
             <groupId>com.google.code.gson</groupId>
             <artifactId>gson</artifactId>
           </exclusion>
+          <exclusion>
+            <groupId>com.google.errorprone</groupId>
+            <artifactId>error_prone_annotations</artifactId>
+          </exclusion>
+          <exclusion>
+            <groupId>io.grpc</groupId>
```
Comment (t0yv0) [inline tests/examples/minimal/pom.xml:83]: Ideas why this is needed?

File: sdk/java/pulumi/src/main/java/com/pulumi/core/internal/Urn.java (hunk 4 above)
Comment (dixler) [reply sdk/java/pulumi/src/main/java/com/pulumi/core/internal/Urn.java:200]: correct.

File: tests/examples/minimal/pom.xml (hunk 5 above)
Comment (dixler) [reply tests/examples/minimal/pom.xml:83]: Thanks for the review. There's a git commit message detailing this, but tl;dr it fixes the minimal example test.

File: sdk/java/pulumi/src/main/java/com/pulumi/core/internal/Urn.java (hunk 4 above)
Comment (Frassle) [reply sdk/java/pulumi/src/main/java/com/pulumi/core/internal/Urn.java:200]: So pt = ""

Comment (dixler) [reply sdk/java/pulumi/src/main/java/com/pulumi/core/internal/Urn.java]: It turned out that it was a list of length - 1 nulls so the join was nonNull and nonEmpty so it was going past the require, but the overall value was overwritten so the rest of the logic worked.

Fixed it.

File: sdk/java/pulumi/src/main/java/com/pulumi/core/internal/Urn.java [hunk 6]
```diff
@@ -181,7 +181,7 @@ public String toString() {
         @SuppressWarnings("ConstantConditions") // IntelliJ can't understand the custom validators
         public static QualifiedTypeName parse(String qualifiedType) {
             var qualifiedTypeParts = qualifiedType.split(ParentSeparatorRegex, -1); // -1 avoids dropping trailing empty strings
-            require(qp -> qp.length == 1 || qp.length == 2, qualifiedTypeParts,
+            require(qp -> qp.length > 0, qualifiedTypeParts,
                     () -> format("expected qualified type to have 1 or 2 parts, split by '%s', got '%s'",
```
Comment (abhinav) [inline sdk/java/pulumi/src/main/java/com/pulumi/core/internal/Urn.java:185]: The require failure message is now outdated. Please update.

File: sdk/java/pulumi/src/main/java/com/pulumi/core/internal/Urn.java [hunk 7]
```diff
@@ -190,20 +190,28 @@ public static QualifiedTypeName parse(String qualifiedType) {
...
-            if (qualifiedTypeParts.length == 2) {
-                var pt = qualifiedTypeParts[0];
+
+            // Handle parents. URNs can have nested parents which should be joined with a "$".
+            if (qualifiedTypeParts.length >= 2) {
+                // Remove the last qualifiedTypeParts element as it's the type.
+                String[] parentList = new String[qualifiedTypeParts.length - 1];
+
+                // Get only the parent parts of the URN type.
+                System.arraycopy(qualifiedTypeParts, 0, parentList, 0, parentList.length);
```
Comment (abhinav) [inline sdk/java/pulumi/src/main/java/com/pulumi/core/internal/Urn.java:200]: I think you can shorten this with [Arrays.copyOf](https://docs.oracle.com/javase/8/docs/api/java/util/Arrays.html#copyOf-T:A-int-).

```java
var parentList = Arrays.copyOf(qualifiedTypeParts, parentList.length-1)
```

Although seeing that this is just fed into String.join, which accepts an Iterable, you don't need to copy at all. You can create a List view of the array (without copying), and then get a sublist of that:

```java
List<String> parentList = Arrays.asList(qualifiedTypeParts).subList(0, qualifiedTypeParts.length - 1);
var pt = String.join(ParentSeparator, parentList)
```

File: sdk/java/pulumi/src/main/java/com/pulumi/core/internal/Urn.java (hunk 2 above)
Comment (abhinav) [reply sdk/java/pulumi/src/main/java/com/pulumi/core/internal/Urn.java:151]: Consider clarifying with a comment here that parent is the full "all parents" string, and not just the last parent.
We should consider renaming this to parents if that won't break any callers. (This doesn't look like it's exposed so it should be fine?)

File: tests/examples/minimal/pom.xml (hunk 5 above)
Comment (t0yv0) [reply tests/examples/minimal/pom.xml:83]: In that case this might belong in a separate PR? Is it failing on master or why did it start failing with the changes? The minimal example test is doing double-duty as a canary for misaligned dependencies, and I'm worried this change papers over that. Misaligned dependencies sometimes result in funny breakage for users depending on their maven import order of pulumi dips.

 I can fill you in on the back-story here.

**Review by t0yv0 — CHANGES_REQUESTED** [review]
"Fix example test minimal" is incorrect as it papers over a dependency convergence error. 

Can we get grpc-stub 1.54.0 and grpc-core 1.52.0 to line up please instead so that dependency convergence checking continues to cover any discrepancies we might have.

Also it does not belong in this PR it seems like.

File: tests/examples/minimal/pom.xml (hunk 5 above)
Comment (dixler) [reply tests/examples/minimal/pom.xml:83]: I'll paper-over the commit, but leave it in the history before squashing so the details are still in this PR.

**Review by t0yv0 — APPROVED** [review]
