### PR TITLE
Exclude Non-Loadable Packages from ClassLoader. Fixes #issue 1385

### LINKED ISSUE #1385: ClassLoader loads all packages presented in pom
### What happened?

We used a packages wihich contains other not used packages, so these packages is not loaded by maven and therefore  the class loader has a problem to load it. This will some out as a error on packages problem:
    SEVERE: Running program [PID: 13236](unknown) failed with an unhandled exception:
    java.lang.IllegalStateException: Failed to load class 'org.apache.commons.compress.harmony.pack200.NewAttribute$ErrorAttribute' (package: 'org.apache.commons.compress.harmony.pack200') from class path: org/objectweb/asm/Attribute

### Example

It is pom.xml excluding a package. We would like to only de it sometimes, because we have multiple class providers etc.   
 <dependency>
      <groupId>com.github.docker-java</groupId>
      <artifactId>docker-java-core</artifactId>
      <exclusions>
        <exclusion>
          <groupId>org.apache.commons</groupId>
          <artifactId>commons-compress</artifactId>
        </exclusion>
      </exclusions>
    </dependency>

### Output of `pulumi about`

CLI          
Version      3.112.0
Go Version   go1.22.1
Go Compiler  gc

Plugins
NAME        VERSION
aws         6.40.0
command     0.10.0
eks         2.7.1
java        unknown
kubernetes  4.13.1

Host
OS       Microsoft Windows 11 Pro
Version  10.0.22631 Build 22631
Arch     x86_64

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by andreaspartisia**
# Description

We encountered an issue with the package loader that loads every package indiscriminately, instead of using the Maven class loader's smart loading. This is a known problem, and while some packages have already been excluded, the process requires a merge request for each exclusion. Therefore, we identified the need for a faster and more dynamic exclusion mechanism.

This fix introduces a system property string containing a comma-separated list of packages to exclude. By setting this property, the specified packages will be excluded from the loaded packages.

Fixes #1385

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works

- [x] I have updated the [CHANGELOG-PENDING](https://github.com/pulumi/pulumi/blob/master/CHANGELOG_PENDING.md) file with my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

File: sdk/java/pulumi/src/main/java/com/pulumi/serialization/internal/ResourcePackages.java [hunk 1]
```diff
@@ -158,7 +158,21 @@ private static boolean excludePackages(ClassInfo c) {
                 && !c.getPackageName().equals("net.bytebuddy")
                 && !c.getPackageName().startsWith("net.bytebuddy.")
                 && !c.getPackageName().startsWith(Resource.class.getPackageName())
-                && !c.getPackageName().startsWith(EngineGrpc.class.getPackageName());
+                && !c.getPackageName().startsWith(EngineGrpc.class.getPackageName())
+                && !excludePackagesFromProperties(c);
+    }
+
+    private static boolean excludePackagesFromProperties(ClassInfo c) {
+        String packages = System.getProperty("ADDITIONAL_EXCLUDES");
```
Comment (justinvp) [inline sdk/java/pulumi/src/main/java/com/pulumi/serialization/internal/ResourcePackages.java:166]: Should we pick a better name than `ADDITIONAL_EXCLUDES` for this? Is there a standard idiomatic naming convention that most other Java libraries typically use for system properties? For example, wondering if this should be something like `pulumi.resourcepackages.excludes` or `pulumi.classloader.excludes` or something like that?

File: sdk/java/pulumi/src/main/java/com/pulumi/serialization/internal/ResourcePackages.java [hunk 2]
```diff
@@ -158,7 +158,21 @@ private static boolean excludePackages(ClassInfo c) {
...
+        if (packages != null) {
+            String[] items = packages.split(",");
+            for (String item : items){
```
Comment (justinvp) [inline sdk/java/pulumi/src/main/java/com/pulumi/serialization/internal/ResourcePackages.java:169]: Wondering if we should trim whitespace from `item`?

**Review by justinvp — CHANGES_REQUESTED** [review]
Thanks for the contribution! I left some review comments. This also needs a test before we can merge it.

File: sdk/java/pulumi/src/main/java/com/pulumi/serialization/internal/ResourcePackages.java (hunk 1 above)
Comment (andreaspartisia) [reply sdk/java/pulumi/src/main/java/com/pulumi/serialization/internal/ResourcePackages.java:166]: Yes this is a very valid point, I think pulumi.resourcepackages.excludes fit the purpose very well.

**Comment by andreaspartisia** [comment]
Thanks for the review @justinvp

I have corrected it now and made a test for a the exclusion of packages.

**Review by justinvp — APPROVED** [review]
Looks good to me. Thanks!

@andreaspartisia, looks like there's a conflict with the `pulumi` submodule. Can you revert that change?

**Comment by andreaspartisia** [comment]
Yes @justinvp it has been updated now.

**Comment by andreaspartisia** [comment]
@justinvp 
Do you have time to look at this again?

**Comment by justinvp** [comment]
@andreaspartisia, thanks for your patience!

I opened a temp PR to run the tests in CI and the new test is failing:

https://github.com/pulumi/pulumi-java/actions/runs/10464711824/job/28978759154?pr=1412#step:12:376

```
ResourcePackagesTest > ExcludedResource() FAILED
    java.lang.AssertionError: Test resource was found
        at com.pulumi.serialization.internal.ResourcePackagesTest.ExcludedResource(ResourcePackagesTest.java:91)
```

**Comment by andreaspartisia** [comment]
Thanks for the reminder @justinvp 
It was because all test used the same JVM in parallel testing, so they polluted each other, but I have made my test run in it's own JWM, so it's fine now.
I hope you have time to look at it again.

**Comment by andreaspartisia** [comment]
@justinvp do you have time to look at it again or do one of your colleagues have time for it?

**Review by justinvp — APPROVED** [review]
LGTM! I'll get it merged after reviewing the test run.

Note: we were running into some unrelated lint issues in CI in this repo yesterday that we may need to fix separately, so it may be another day or so. Thanks for your patience and thanks again for addressing this!
