### PR TITLE
Fix a regression in tolerating missing fields

### LINKED ISSUE #821: example https://github.com/pulumi/examples/tree/master/aws-java-eks-minimal fails to run
### What happened?

The aws-java-eks-minimal example stopped working.  Downgrading to ```com.pulumi:pulumi 0.5.2``` makes it work again so there is a regression introduced in the Java SDK somewhere between 0.5.2 and 0.5.3. The preview of `aws:ec2/getVpc:getVpc result` hits a null check and fails to deserialize.

### Steps to reproduce

Clone `pulumi/exampes`, `cd aws-java-eks-minimal` and `pulumi preview`

### Expected Behavior

It is supposed to create k8s cluster in aws

### Actual Behavior

```
C:\temp\examples\aws-java-eks-minimal>pu
Previewing update (dev)

View Live: https://app.pulumi.com/nagkumar/eks-minimal/dev/previews/9ce040d0-6d92-41dc-bdfd-d83caa400ff9

     Type                 Name             Plan       Info
 +   pulumi:pulumi:Stack  eks-minimal-dev  create     2 errors; 44 messages

Diagnostics:
  pulumi:pulumi:Stack (eks-minimal-dev):
    Aug 29, 2022 3:39:19 PM com.pulumi.deployment.internal.DeploymentImpl$DefaultEngineLogger errorAsync
    SEVERE: Running program [PID: 2796](unknown) failed with an unhandled exception:
    java.lang.UnsupportedOperationException: Convert [aws:ec2/getVpc:getVpc result]: Error converting 'com.google.common.collect.RegularImmutableMap' to 'TypeShape{type=class com.pulumi.aws.ec2.outputs.GetVpcResult, parameters=[]}'. Unexpected exception: null
        at com.pulumi.serialization.internal.Converter.convertObjectUntyped(Converter.java:119)
        at com.pulumi.serialization.internal.Converter.convertValue(Converter.java:86)
        at com.pulumi.deployment.internal.DeploymentImpl$Invoke.parseInvokeResponse(DeploymentImpl.java:482)
        at com.pulumi.deployment.internal.DeploymentImpl$Invoke.lambda$invoke$1(DeploymentImpl.java:473)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
        at net.javacrumbs.futureconverter.guavacommon.GuavaFutureUtils$ListenableFutureBackedValueSourceFuture$1.onSuccess(GuavaFutureUtils.java:139)
        at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1138)
        at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
        at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1270)
        at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1038)
        at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:783)
        at io.grpc.stub.ClientCalls$GrpcFuture.set(ClientCalls.java:558)
        at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:531)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:553)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:68)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:739)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:718)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
    Caused by: java.lang.IllegalStateException: Unexpected exception: null
        at com.pulumi.serialization.internal.Converter.lambda$tryConvertObjectInner$7(Converter.java:450)
        at java.base/java.util.HashMap.forEach(HashMap.java:1336)
        at com.pulumi.serialization.internal.Converter.tryConvertObjectInner(Converter.java:409)
        at com.pulumi.serialization.internal.Converter.convertObjectUntyped(Converter.java:115)
        ... 23 more
    Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.pulumi.serialization.internal.Converter.lambda$tryConvertObjectInner$7(Converter.java:441)
        ... 26 more
    Caused by: java.lang.NullPointerException
        at java.base/java.util.Objects.requireNonNull(Objects.java:221)
        at com.pulumi.aws.ec2.outputs.GetVpcResult$Builder.state(GetVpcResult.java:291)
        ... 31 more

    error: Running program [PID: 2796](unknown) failed with an unhandled exception:
    java.lang.UnsupportedOperationException: Convert [aws:ec2/getVpc:getVpc result]: Error converting 'com.google.common.collect.RegularImmutableMap' to 'TypeShape{type=class com.pulumi.aws.ec2.outputs.GetVpcResult, parameters=[]}'. Unexpected exception: null
        at com.pulumi.serialization.internal.Converter.convertObjectUntyped(Converter.java:119)
        at com.pulumi.serialization.internal.Converter.convertValue(Converter.java:86)
        at com.pulumi.deployment.internal.DeploymentImpl$Invoke.parseInvokeResponse(DeploymentImpl.java:482)
        at com.pulumi.deployment.internal.DeploymentImpl$Invoke.lambda$invoke$1(DeploymentImpl.java:473)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
        at net.javacrumbs.futureconverter.guavacommon.GuavaFutureUtils$ListenableFutureBackedValueSourceFuture$1.onSuccess(GuavaFutureUtils.java:139)
        at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1138)
        at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
        at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1270)
        at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1038)
        at com.google.common.util.concurrent.AbstractFuture.set(AbstractFuture.java:783)
        at io.grpc.stub.ClientCalls$GrpcFuture.set(ClientCalls.java:558)
        at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:531)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:553)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:68)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:739)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:718)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
    Caused by: java.lang.IllegalStateException: Unexpected exception: null
        at com.pulumi.serialization.internal.Converter.lambda$tryConvertObjectInner$7(Converter.java:450)
        at java.base/java.util.HashMap.forEach(HashMap.java:1336)
        at com.pulumi.serialization.internal.Converter.tryConvertObjectInner(Converter.java:409)
        at com.pulumi.serialization.internal.Converter.convertObjectUntyped(Converter.java:115)
        ... 23 more
    Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.pulumi.serialization.internal.Converter.lambda$tryConvertObjectInner$7(Converter.java:441)
        ... 26 more
    Caused by: java.lang.NullPointerException
        at java.base/java.util.Objects.requireNonNull(Objects.java:221)
        at com.pulumi.aws.ec2.outputs.GetVpcResult$Builder.state(GetVpcResult.java:291)
        ... 31 more
    error: an unhandled error occurred: 'd:\Apps\Dev\langs\java\bldeng\mvn\bin\mvn.cmd d:\Apps\Dev\langs\java\bldeng\mvn\bin\mvn.cmd -Dorg.slf4j.simpleLogger.defaultLogLevel=warn --no-transfer-progress compile exec:java' exited with non-zero exit code: 1
```

### Output of `pulumi about`

```
CLI          
Version      3.38.0
Go Version   go1.19
Go Compiler  gc

Plugins
NAME        VERSION
aws         5.13.0
eks         0.37.1
java        unknown
kubernetes  3.22.0-alpha.1661453084+94c160dd

Host     
OS       darwin
Version  12.5.1
Arch     x86_64

This project is written in java: executable='/Users/anton/.nix-profile/bin/java' version='openjdk 11.0.11 2021-04-20 LTS
OpenJDK Runtime Environment Zulu11.48+21-CA (build 11.0.11+9-LTS)
OpenJDK 64-Bit Server VM Zulu11.48+21-CA (build 11.0.11+9-LTS, mixed mode)' maven='Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)' gradle='7.4' java='/Users/anton/.nix-profile/bin/java' javac='11.0.11'

Current Stack: dev1

Found no resources associated with dev1

Found no pending operations associated with dev1

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/t0yv0
User           t0yv0
Organizations  t0yv0, pulumi

No dependencies found

Pulumi locates its logs in /var/folders/mb/s1jx27m10t3082fqclpgytt80000gn/T/ by default
```

### Additional context

```mvn dependency:tree```

```
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------< com.pulumi:aws-java-eks-minimal >-------------------
[INFO] Building aws-java-eks-minimal 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ aws-java-eks-minimal ---
[WARNING] The artifact xml-apis:xml-apis:jar:2.0.2 has been relocated to xml-apis:xml-apis:jar:1.0.b2
[INFO] com.pulumi:aws-java-eks-minimal:jar:1.0-SNAPSHOT
[INFO] +- com.pulumi:pulumi:jar:0.5.4:compile
[INFO] |  +- io.grpc:grpc-protobuf:jar:1.38.0:runtime
[INFO] |  |  +- io.grpc:grpc-api:jar:1.38.0:runtime
[INFO] |  |  |  \- io.grpc:grpc-context:jar:1.38.0:runtime
[INFO] |  |  +- com.google.api.grpc:proto-google-common-protos:jar:2.0.1:runtime
[INFO] |  |  +- io.grpc:grpc-protobuf-lite:jar:1.38.0:runtime
[INFO] |  |  +- com.google.errorprone:error_prone_annotations:jar:2.4.0:compile
[INFO] |  |  \- org.codehaus.mojo:animal-sniffer-annotations:jar:1.19:runtime
[INFO] |  +- io.grpc:grpc-stub:jar:1.38.0:runtime
[INFO] |  +- com.google.code.findbugs:jsr305:jar:3.0.2:compile
[INFO] |  +- net.javacrumbs.future-converter:future-converter-java8-guava:jar:1.2.0:runtime
[INFO] |  |  +- net.javacrumbs.future-converter:future-converter-common:jar:1.2.0:runtime
[INFO] |  |  +- net.javacrumbs.future-converter:future-converter-java8-common:jar:1.2.0:runtime
[INFO] |  |  \- net.javacrumbs.future-converter:future-converter-guava-common:jar:1.2.0:runtime
[INFO] |  +- com.google.guava:guava:jar:31.1-jre:compile
[INFO] |  |  +- com.google.guava:failureaccess:jar:1.0.1:compile
[INFO] |  |  +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:compile
[INFO] |  |  +- org.checkerframework:checker-qual:jar:3.12.0:compile
[INFO] |  |  \- com.google.j2objc:j2objc-annotations:jar:1.3:compile
[INFO] |  +- com.google.code.gson:gson:jar:2.8.9:compile
[INFO] |  +- com.google.protobuf:protobuf-java:jar:3.21.1:runtime
[INFO] |  +- com.google.protobuf:protobuf-java-util:jar:3.21.1:runtime
[INFO] |  \- io.grpc:grpc-netty-shaded:jar:1.38.0:runtime
[INFO] |     \- io.grpc:grpc-core:jar:1.38.0:runtime (version selected from constraint [1.38.0,1.38.0])
[INFO] |        +- com.google.android:annotations:jar:4.1.1.4:runtime
[INFO] |        \- io.perfmark:perfmark-api:jar:0.23.0:runtime
[INFO] +- com.pulumi:aws:jar:5.13.0:compile
[INFO] +- com.pulumi:kubernetes:jar:3.22.0-alpha.1661453084+94c160dd:compile
[INFO] \- com.pulumi:eks:jar:0.37.1:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.653 s
[INFO] Finished at: 2022-08-29T10:44:07-04:00
[INFO] ------------------------------------------------------------------------
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### LINKED ISSUE #839: Get Event Hub Shared Access Keys fail due to pulumi forcing alias primary and secondary keys to be non null.
### What happened?

Get Event Hub Shared Access Keys fail due to pulumi forcing alias primary and secondary keys to be non null.

### Steps to reproduce

CLI Command: 
az eventhubs eventhub authorization-rule keys list --resource-group my-resource-group namespace-name my-namespace --eventhub-name my-event-hub --name my-shared-key

Response:
{
  "aliasPrimaryConnectionString": null,
  "aliasSecondaryConnectionString": null,
  "keyName": "my-shared-key",
  "primaryConnectionString": "Endpoint=sb://my-namespace.servicebus.windows.net/;SharedAccessKeyName=my-shared-key;SharedAccessKey=xxxxxxxxxx;EntityPath=my-event-hub",
  "primaryKey": “xxxxxxxxxxxx”,
  "secondaryConnectionString": "Endpoint=sb:/my-namespace.servicebus.windows.net/;SharedAccessKeyName=my-shared-key;SharedAccessKey=xxxxxxxxxxxxxxx;EntityPath=my-event-hub",
  "secondaryKey": “xxxxxxxxxxx”xxxx
}

Pulumi Code:

EventhubFunctions.listEventHubKeys(ListEventHubKeysArgs.builder()
        .resourceGroupName(Output.of("my-resource-group"))
        .namespaceName(Output.of("my-namespace"))
        .eventHubName(Output.of("my-event-hub"))
        .authorizationRuleName(Output.of("my-shared-key"))
        .build());

Error after pulumi up:

java.lang.UnsupportedOperationException: Convert [azure-native:eventhub:listEventHubKeys result]: Error converting 'com.google.common.collect.RegularImmutableMap' to 'TypeShape{type=class com.pulumi.azurenative.eventhub.outputs.ListEventHubKeysResult, parameters=[]}'. Unexpected exception: null
        at com.pulumi.serialization.internal.Converter.convertObjectUntyped(Converter.java:119)
        at com.pulumi.serialization.internal.Converter.convertValue(Converter.java:86)
        at com.pulumi.deployment.internal.DeploymentImpl$Invoke.parseInvokeResponse(DeploymentImpl.java:482)
..............
    Caused by: java.lang.NullPointerException
        at java.base/java.util.Objects.requireNonNull(Objects.java:222)
        at com.pulumi.azurenative.eventhub.outputs.ListEventHubKeysResult$Builder.aliasSecondaryConnectionString(ListEventHubKeysResult.java:134)
        ... 31 more

### Expected Behavior

Successful with no exception

### Actual Behavior

Exception because the alias secondary key is assumed to be non null.

### Output of `pulumi about`

CLI          
Version      3.39.3
Go Version   go1.19.1
Go Compiler  gc

Plugins
NAME          VERSION
azure-native  1.74.0
java          unknown

Host     
OS       darwin
Version  12.6
Arch     x86_64

This project is written in java: executable='/usr/bin/java' version='openjdk 14.0.2 2020-07-14
OpenJDK Runtime Environment (build 14.0.2+12-46)
OpenJDK 64-Bit Server VM (build 14.0.2+12-46, mixed mode, sharing)' maven='Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)' java='/usr/bin/java' javac='14.0.2'

### Additional context

_No response_

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by t0yv0**
# Description

Pulumi SDK versions after 0.5.2 do not work well with the most recent style of resource builders; there is a regression where the SDK stopped tolerating missing and null data when deserializing provider responses. This PR fixes the regression. 

Fixes #821 

Possibly fixes #839 and #836

Typical trace fixed here:

```
    Caused by: java.lang.IllegalStateException: Unexpected exception: null
        at com.pulumi.serialization.internal.Converter.lambda$tryConvertObjectInner$7(Converter.java:450)
        at java.base/java.util.HashMap.forEach(HashMap.java:1336)
        at com.pulumi.serialization.internal.Converter.tryConvertObjectInner(Converter.java:409)
        at com.pulumi.serialization.internal.Converter.convertObjectUntyped(Converter.java:115)
        ... 23 more
    Caused by: java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.pulumi.serialization.internal.Converter.lambda$tryConvertObjectInner$7(Converter.java:441)
        ... 26 more
    Caused by: java.lang.NullPointerException
        at java.base/java.util.Objects.requireNonNull(Objects.java:221)
        at com.pulumi.aws.ec2.outputs.GetVpcResult$Builder.state(GetVpcResult.java:291)
        ... 31 more
```

## Checklist

- [ ] I have added tests that prove my fix is effective or that my feature works

- [ ] I have updated the [CHANGELOG-PENDING](https://github.com/pulumi/pulumi/blob/master/CHANGELOG_PENDING.md) file with my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

**Review by dixler — APPROVED** [review]
LGTM

File: sdk/java/pulumi/src/main/java/com/pulumi/serialization/internal/Converter.java [hunk 1]
```diff
@@ -428,7 +428,15 @@ private Object tryConvertObjectInner(
...
                             TypeShape.extract(extractSetterParameter(setters.get(name)))
                     );
-                    setters.get(name).invoke(builder, convertedArgument);
+                    // Builders generated by Pulumi codegen typically
+                    // null checks with requireNonNull, so invoking
+                    // the builder method with null will throw. But
+                    // Pulumi SDK needs to tolerate missing data, so
+                    // we err on the side of skipping the builder call
+                    // when the argument is null.
+                    if (convertedArgument != null) {
```
Comment (pawelprazak) [inline sdk/java/pulumi/src/main/java/com/pulumi/serialization/internal/Converter.java:437]: Note: this might change semantics in a subtle way, because it skips calling setter on @Nullable params as well. Not sure if in practice this will ever make a difference, because I don't think we'll have "dirty" builders, so the field will be null anyway.

I'd guess this will work fine.

**Review by pawelprazak — COMMENTED** [review]
slight semantics change, but should work

File: sdk/java/pulumi/src/main/java/com/pulumi/serialization/internal/Converter.java (hunk 1 above)
Comment (t0yv0) [reply sdk/java/pulumi/src/main/java/com/pulumi/serialization/internal/Converter.java:437]: Yes, I figured that not calling the method leaves the value null as before. So it's the same behavior.
