### PR TITLE
Fixes missing gradle fields for 3rd party providers

### LINKED ISSUE #1118: Third Party Publishers not supported
### What happened?

not using `Pulumi` as the publisher in `resources.go` leads to an incomplete `build.gradle` file.

specifically the publishing configuration:
```java
publishing {
    publications {
        mainPublication(MavenPublication) {
            groupId = ""
            artifactId = ""
            version = resolvedVersion
            from components.java
            artifact sourcesJar
            artifact javadocJar

            pom {
                inceptionYear = ""
                name = ""
                packaging = "jar"
                description = ""

                url = "https://github.com/muhlba91/pulumi-proxmoxve"

                scm {
                    connection = "git@github.com/muhlba91/pulumi-proxmoxve.git"
                    developerConnection = "git@github.com/muhlba91/pulumi-proxmoxve.git"
                    url = "https://github.com/muhlba91/pulumi-proxmoxve"
                }

                licenses {
                    license {
                        name = "The Apache License, Version 2.0"
                        url = "http://www.apache.org/licenses/LICENSE-2.0.txt"
                    }
                }

                developers {
                    developer {
                        id = ""
                        name = ""
                        email = ""
                    }
                }
            }
        }
    }
}
```

in comparison the GCP provider sets `Pulumi` as publisher and ends up with correct parameters: https://github.com/pulumi/pulumi-gcp/blob/master/sdk/java/build.gradle#LL79C1-L120C2

the reason is a hard-coded check for `Pulumi` publishers in https://github.com/pulumi/pulumi-java/blob/main/pkg/codegen/java/templates_gradle.go#L119-L130.

### Expected Behavior

auto-generation of java code and `build.gradle` supports using a third-party publisher, e.g. by setting the required parameters in the `JavaBridge` in `resources.go`. (= parameters in https://github.com/pulumi/pulumi-java/blob/main/pkg/codegen/java/templates_gradle.go#L119-L130 can be sourced from the config)

### Steps to reproduce

1. set the `Publisher` property in `resources.go` to something else than `Pulumi`
2. trigger code-generation

### Output of `pulumi about`

N/A

### Additional context

example of a current WIP third-party provider supporting Java is https://github.com/muhlba91/pulumi-proxmoxve/pull/65

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by dixler**
# Description

This PR adds `groupId`, `artifactId`, and `description` to Gradle publications section for non-pulumi (3rd-party) publishers.

Fixes #1118 

## Checklist

- [x] I have added tests that prove my fix is effective or that my feature works

- [x] I have updated the [CHANGELOG-PENDING](https://github.com/pulumi/pulumi/blob/master/CHANGELOG_PENDING.md) file with my change

- [ ] Yes, there are changes in this PR that warrants bumping the Pulumi Service API version

### CODE REVIEW

**Review by Frassle — COMMENTED** [review]
Looks reasonable but I know nada about gradle. @t0yv0 can you quickly sanity check this?

File: pkg/codegen/java/templates_gradle.go [hunk 1]
```diff
@@ -116,15 +118,19 @@ func newGradleTemplateContext(
 		ctx.LicenceURL = "http://www.apache.org/licenses/LICENSE-2.0.txt"
 	}
 
+	ctx.GroupID = packageInfo.BasePackage
```
Comment (t0yv0) [inline pkg/codegen/java/templates_gradle.go:121]: // The prefix of the Java package to generate.
	//
	// Defaults to "com.pulumi".
	//
	// The generated Java code will start with:
	//
	//     package ${BasePackage}.${pkg.Name};
	//
	// Note that pkg.Name is coming from the Schema.
	//
	// For example, if the package is named "azuread" then the
	// generated code will be placed under:
	//
	//     package com.pulumi.azuread
	//
	// And if BasePackage is set to "com.myorg" then the generated
	// code will instead be placed under:
	//
	//     package com.myorg.azuread
	//
	BasePackage string `json:"basePackage"`

Hm, It's probably reasonable to default GroupID to BasePackage

**Review by t0yv0 — APPROVED** [review]
